### ISSUE TITLE
Home Assistant stop after some time..

### ISSUE THREAD

**Issue by dlwoals131** [h4/LYWSD02-home-assistant#10]
Good evening~
I really appreciate your work! And I almost did the integration.
But still have some issues.. 

1. Successfully connected yesterday 21:38PM. After HA connect with lywsd02, HA operation is not permitted around 3AM. and HA continues to stop every 6 hours .

2019-11-19 03:19:57 WARNING (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
PermissionError: [Errno 1] Operation not permitted
2019-11-19 04:28:28 WARNING (Thread-2) [pychromecast.socket_client] [HOMEHUB:8009] Heartbeat timeout, resetting connection

![캡처](https://user-images.githubusercontent.com/54792185/69141892-008be200-0b09-11ea-8de8-2298bcb6d20f.PNG)

2. HA shows continues warning message same as below(WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf4320416b5 is taking over 10 seconds)

**home-assistant.log**

2019-11-18 21:38:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for lywsd02 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-18 21:39:21 WARNING (MainThread) [homeassistant.components.weather] Setup of platform met is taking over 10 seconds.
2019-11-18 21:39:21 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform lywsd02 is taking over 10 seconds.
2019-11-18 21:39:21 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2019-11-18 21:39:21 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/ returned 
2019-11-18 21:39:21 ERROR (MainThread) [homeassistant.components.met.weather] Retrying in 15 minutes
2019-11-18 21:40:09 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf4320416b5 is taking over 10 seconds
2019-11-18 21:45:44 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf4320416b5 is taking over 10 seconds
2019-11-19 03:06:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf43203fa82 is taking over 10 seconds
2019-11-19 03:06:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf43203fa82 is taking over 10 seconds
2019-11-19 03:07:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf4320416b5 is taking over 10 seconds
2019-11-19 03:07:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.808204522cf43203fa82 is taking over 10 seconds
2019-11-19 03:19:57 WARNING (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
PermissionError: [Errno 1] Operation not permitted
2019-11-19 04:28:28 WARNING (Thread-2) [pychromecast.socket_client] [HOMEHUB:8009] Heartbeat timeout, resetting connection

Please help me~~

**Comment by h4** [comment]
Hi. This log messages are not related to my integration. Looks like you have Google Chromecast or Google Home devices and it discard connections.

But as I see, lywsd02 data stop changing. In most case it relates to bluetooth adapter. I have same issue on my raspberry pi 4, but did not have on my home server. I still try to find the reason of it behavior.
